name: CD Pipeline

on:
  repository_dispatch:
    types: [go-pypi]
jobs:
  continuous_deployment:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.release_tag }}
      - uses: pdm-project/setup-pdm@v4
      - name: Publish package distributions to PyPI
        run: pdm publish
